file(READ ${NM_APP_VERSION_H} header)
string(REGEX MATCH "#define[ \t]+NM_APP_VERSION_MAJ[ \t]+[0-9]+" VERSION_MAJ_LINE "${header}")
string(REGEX MATCH "#define[ \t]+NM_APP_VERSION_MIN[ \t]+[0-9]+" VERSION_MIN_LINE "${header}")
string(REGEX MATCH "#define[ \t]+NM_APP_VERSION_REV[ \t]+[0-9]+" VERSION_REV_LINE "${header}")
string(REGEX MATCH "[0-9]+" VERSION_MAJ "${VERSION_MAJ_LINE}")
string(REGEX MATCH "[0-9]+" VERSION_MIN "${VERSION_MIN_LINE}")
string(REGEX MATCH "[0-9]+" VERSION_REV "${VERSION_REV_LINE}")

execute_process(COMMAND git log --pretty=format:'%H' -n 1
                OUTPUT_VARIABLE GIT_HASH
                ERROR_QUIET)

if ("${GIT_HASH}" STREQUAL "")
    set(GIT_HASH "unknown")
    set(GIT_DIFF "")
else()
    string(STRIP "${GIT_HASH}" GIT_HASH)
    string(REPLACE "'" "" GIT_HASH ${GIT_HASH})

    execute_process(
        COMMAND sh -c "git diff --quiet --exit-code || echo +"
        OUTPUT_VARIABLE GIT_DIFF)
    if (NOT "${GIT_DIFF}" STREQUAL "")
        string(REPLACE "\n" "" GIT_DIFF ${GIT_DIFF})
    endif()
endif()

set(VERSION
"/*
 * DO NOT EDIT THIS FILE
 * THE CONTENT IS AUTO-GENERATED
 */
const char nm_app_version[]=\"${VERSION_MAJ}.${VERSION_MIN}.${VERSION_REV}-${GIT_DIFF}${GIT_HASH}\";\n\n")

if(EXISTS ${NM_APP_VERSION_C})
    file(READ ${NM_APP_VERSION_C} VERSION_)
else()
    set(VERSION_ "")
endif()

if (NOT "${VERSION}" STREQUAL "${VERSION_}")
    file(WRITE ${NM_APP_VERSION_C} "${VERSION}")
endif()